[package]
name = "ipfs-cid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cid = { version = "0.5.0", default-features = false }
thiserror = "1.0.41"
ipfs-unixfs = "0.2.0"
bs58 = "0.5.0"
